server:
    port: 9528

spring:
    application:
        name: cloudalibaba-sentinel-gateway     # sentinel+gataway整合Case
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
        sentinel:
            transport:
                dashboard: localhost:8080
#            scg:
#                fallback:
#                    # 两种模式，一种是response返回文字提示信息，
#                    # 一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
#                    mode: response
#                    ## 响应的状态
#                    response-status: 200
#                    ## 响应体
#                    response-body: '{"code": 200,"message": "yaml配置方式，自定义限流信息"}'
            datasource:
                ds1:
                    nacos:
                        server-addr: localhost:8848
                        dataId: ${spring.application.name}
                        groupId: DEFAULT_GROUP
                        data-type: json
                        rule-type: flow
        
        #                    mode: redirect
#                    ## 跳转的URL
#                    redirect: http://www.baidu.com
        gateway:
            routes:
                - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
                  uri: http://localhost:9001                #匹配后提供服务的路由地址
                  predicates:
                      - Path=/pay/**                      # 断言，路径相匹配的进行路由
